Talisman.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Talisman.Domain.Abstract;
using Talisman.Domain.Entities;
using Talisman.WebUI.Models;
using System.Web.Security;
using Talisman.Domain.Concrete;
using System.IO;
using System.Web.Mvc.Html;
using System.Drawing;
using System.Drawing.Imaging;


namespace Talisman.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private List<Tovar> Tovars1;
        private List<Categorie> Categories;
        private List<Photo> Photos1;
        private List<Article> Articles;
        private List<FeedBack> FeedBacks;
        private List<Service> Services1;
        private List<New> News1;
        private Over Over1;
        private NewRepository nrepo;
        private GData3 g;
        //IRepository repo;
        public AdminController()
        {
            nrepo = new NewRepository();
            g = new GData3();
            Tovars1 = g.Tovars;
            Categories = g.Categories;
            Photos1 = g.Photos;
            Articles = g.Articles;
            //repo = r;
            FeedBacks = g.FeedBacks;
            Services1 = g.Services;
            News1 = g.News;
            Over1 = g.Over;
        }


        public ActionResult ListCategories()
        {
            //var Categories = (HttpContext.Application["GlobalData"] as GlobalData).Categories;
            var model = Categories;
            return View(model);
        }

        public ActionResult EditCategory(int CategoryId)
        {
            //var Categories = (HttpContext.Application["GlobalData"] as GlobalData).Categories;
            var model = Categories.Where(c => c.CategoryId == CategoryId).FirstOrDefault();
            if (model == null)
            {
                return View("AdminError");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditCategory(Categorie category)
        {
            if (ModelState.IsValid)
            {
                category.LM = DateTime.Now;
                var result = await nrepo.Update<Categorie>(category);//repo.SaveCategory(category);
                if (result.Success)
                {
                    TempData["messageCreateOk"] = "Изменения успешно сохранены.";
                    return RedirectToAction("ListCategories");
                }
                else
                {
                    return View("AdminErr", result.Errormessage);
                }

            }
            return View(category);
        }

        public ActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CreateCategory(Categorie category)
        {
            if (ModelState.IsValid)
            {
                category.CategoryId = 0;
                category.LM = DateTime.Now;                
                var result = await nrepo.Insert<Categorie>(category);
                if (result.Success)
                {
                    TempData["messageCreateOk"] = "Категория успешно создана.";
                    return RedirectToAction("ListCategories");
                }
                else
                {
                    return View("AdminErr", (object)result.Errormessage);
                }

            }
            return View(category);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteCategory(int categoryId)
        {

            if (categoryId > 0)
            {
                var cou = Tovars1.Where(c => c.CategoryId == categoryId).Count();
                if (cou == 0)
                {
                    var r = await nrepo.Delete<Categorie>(categoryId);//repo.DeleteCategory(categoryId);
                    if (!r.Success)
                    {
                        TempData["messageNotDel"] = r.Errormessage;
                    }
                    else
                    {
                        TempData["messageOkDel"] = "Категория успешно удалена";
                    }
                }
                else
                {
                    TempData["messageNotDel"] = "Нельзя удалить категорию, содержащую позиции ассортимента!";
                }
            }
            return RedirectToAction("ListCategories");
        }

        public PartialViewResult Tovars(int categoryId)
        {
            ViewBag.categoryId = categoryId;
            //var Tovars = (HttpContext.Application["GlobalData"] as GlobalData).Tovars;
            //var Photos = (HttpContext.Application["GlobalData"] as GlobalData).Photos;
            var tov = Tovars1.Where(t => t.CategoryId == categoryId).ToArray();
            var ph = Photos1.Select(p => new { p.TovarId, p.PhotoId }).ToArray();
            var t1 = tov.Select(t => t.TovarId);
            var t2 = ph.Select(p => p.TovarId);
            var ex = t1.Except(t2);
            //var ph=repo.Photos.Ex
            //var model = tov.Select(t => new EditTovarViewModel { Tovar = t, 
            //    //PhotoId = 33
            //    PhotoId= ph.Where(p => p.TovarId == t.TovarId).Select(p=>p.PhotoId).FirstOrDefault() 
            //});
            var model = from t in tov.Where(to => to.CategoryId == categoryId)
                        join p in ph
                        on t.TovarId equals p.TovarId
                        select new { t, p } into temp
                        group temp by temp.t.TovarId into g
                        select new EditTovarViewModel { Tovar = g.Select(x => x.t).FirstOrDefault(), PhotoId = g.Min(y => y.p.PhotoId) };
            //var np=model.Except()

            var m = model.Union(ex.Select(e => new EditTovarViewModel { Tovar = tov.Where(t => t.TovarId == e).FirstOrDefault(), PhotoId = 0 }));
            ViewBag.category = Categories.Where(c => c.CategoryId == categoryId).Select(c => c.CategoryName).FirstOrDefault();
            return PartialView(m);
        }

        public async Task<ActionResult> CreateTovar(int categoryId)
        {
            int id = 1;
            //var Categories = (HttpContext.Application["GlobalData"] as GlobalData).Categories;
            var catName = Categories.Where(c => c.CategoryId == categoryId).Select(c => c.CategoryName).FirstOrDefault();
            if (Tovars1.Count() > 0)
            {
                id = (Tovars1.Select(t => t.TovarId).Max()) + 1;
            }

            Tovar tovar = new Tovar { TovarId = 0, CategoryId = categoryId, Name = catName + " модель" + id.ToString(), Visible = false, Describing = "", Price = 0, CEO = "", IsNew = false, LM = DateTime.Now };
            var r = await nrepo.Insert<Tovar>(tovar);//repo.SaveTovar(tovar);
            if (r.Success)
            {
                tovar.TovarId = (int)r.Value;
                return View(tovar);
            }
            else
            {
                return View("AdminErr", (object)r.Errormessage);
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateTovar(Tovar tovar)
        {
            if (ModelState.IsValid)
            {
                //var r = await repo.SaveTovar(tovar);
                if (tovar.Describing == null)
                {
                    tovar.Describing = string.Empty;
                }
                if (tovar.Price == null)
                {
                    tovar.Price = 0;
                }
                tovar.LM = DateTime.Now;
                Result r = null;
                if (tovar.TovarId == 0)
                {
                    r = await nrepo.Insert<Tovar>(tovar);
                }
                else
                {
                    r = await nrepo.Update<Tovar>(tovar);
                }
                if (r.Success)
                {
                    TempData["messageOk"] = "Данные успешно сохранены.";
                }
                else
                {
                    TempData["messageNotOk"] = r.Errormessage;
                }

                return RedirectToAction("EditCategory", new { categoryId = tovar.CategoryId });
            }
            return View(tovar);
        }

        public ActionResult EditTovar(int tovarId)
        {
            // var Tovars = (HttpContext.Application["GlobalData"] as GlobalData).Tovars;
            var tovar = Tovars1.Where(t => t.TovarId == tovarId).FirstOrDefault();
            return View("CreateTovar", tovar);
        }

        public async Task<ActionResult> DeleteTovar(int tovarId, int categoryId)
        {
            var r = await nrepo.Delete<Tovar>(tovarId);//await repo.DeleteTovar(tovarId);
            if (r.Success)
            {
                //g.Tovars = null;
                return RedirectToAction("EditCategory", new { categoryId = categoryId });
            }
            else
            {
                return View("AdminErr");
            }

        }

        public PartialViewResult AddPhoto(int tovarId)
        {
            return PartialView((object)tovarId);
        }
        [HttpPost]
        public async Task<ActionResult> AddPhoto(int tovarId, IEnumerable<HttpPostedFileBase> images = null)
        {
            if (ModelState.IsValid)
            {
                // Photo photo = new Photo { TovarId = tovarId };
                if (images != null)
                {
                    foreach (var i in images)
                    {
                        var photo = new Photo2 { TovarId = tovarId };
                        photo.ImageMimeType = i.ContentType;
                        photo.Image = new byte[i.ContentLength];
                        photo.LM = DateTime.Now;
                        //photo.Mini=                        
                        i.InputStream.Read(photo.Image, 0, i.ContentLength);
                        var r = await nrepo.Insert<Photo2>(photo);//repo.SavePhoto(photo);
                        if (!r.Success)

Talisman.WebUI/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Talisman.Domain.Abstract;
using Talisman.Domain.Entities;
using Talisman.WebUI.Models;
using System.Web.UI;
using Talisman.WebUI;
using Talisman.Domain.Concrete;
using System.Threading.Tasks;

namespace Talisman.WebUI.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    public class ArticlesController : Controller
    {
        //private List<Article> Articles;
        private GData3 g;
        public ArticlesController()
        {
            g = new GData3();
            //Articles = g.Articles;
        }
        // GET: Articles
        //public ActionResult Index()
        //{
        //    return View();
        //}
        // [OutputCache(Duration = 300, Location = OutputCacheLocation.Server)]
        public async Task<ActionResult> Article(string artName=null)
        {
            int id;
            ArtMin ar; 
            if (artName != null&&artName!="")
            {
                ar = g.ArtMins.Where(a => a.Name.Replace(' ', '-').Replace("?", "").Replace(":", "").Replace("`", "").Replace(".", "") == artName).FirstOrDefault();
                if (ar == null)
                {
                    return new HttpNotFoundResult();
                }
                id = ar.Id;
            }
            else
            {                
                ar = g.ArtMins.FirstOrDefault();
                ViewBag.IsDef = true;
            }            
            ViewBag.id = ar.Id;
            var api=new ApiDb2();
            var cont = (await api.ReadArtCont(ar.Id)).Value as string;                       
            var m = new Article { Id = ar.Id, Name = ar.Name, Content = cont };            
            Response.Cache.SetLastModified(g.Get_LM(HeadersFor.Articles));
            return View(m);
        }

        //public ActionResult Article1()
        //{
        //    return View();
        //}
       //  [OutputCache(Duration = 300, Location = OutputCacheLocation.Server)]
        public PartialViewResult ArticleMenu(int id) 
        {
            //var Articles = (HttpContext.Application["GlobalData"] as GlobalData).Articles;
            var list = g.Articles.Select(a => new ArtMenuList { Id = a.Id, ArticleName = a.Name });
            var model = new ArticleMenuViewModel { CurrentId = id, List = list };
            return PartialView(model);
        }
         
    }
}

Talisman.WebUI/Controllers/FeedBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Talisman.Domain.Abstract;
using Talisman.Domain.Entities;
using System.Threading.Tasks;
using Talisman.Domain.Concrete;
namespace Talisman.WebUI.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    public class FeedBackController : Controller
    {
        private GData3 g;
        //IRepository repo;
        public FeedBackController()
        {
            g = new GData3();
            //this.g = g;
        }
        // GET: FeedBack
        public ActionResult List() 
        {
            var model = g.FeedBacks.Where(f=>f.Visible);
            Response.Cache.SetLastModified(g.Get_LM(HeadersFor.Feedbacks));
            return View(model);
        }

        public PartialViewResult AddFeedBack()
        {
            return PartialView();
        }
        [HttpPost]
        public async Task<PartialViewResult> AddFeedBack(FeedBack fb)
        {
            if (ModelState.IsValid)
            {
                fb.Id = 0;
                fb.Date = DateTime.Now;
                if (fb.Contacts == null)
                {
                    fb.Contacts = "";
                }
                //var res = await repo.SaveFeedBack(fb);
                var repo = new NewRepository();
                var res = await repo.Insert<FeedBack>(fb);
                if (res.Success)
                {
                    ViewBag.cl = "fbOk";
                    ViewBag.mess = "Спасибо! Ваш отзыв успешно отправлен на модерацию.";
                    return PartialView("FBres");
                }
                else
                {
                    ViewBag.cl = "fbErr";
                    ViewBag.mess = res.Errormessage;
                }
                return PartialView("FBres");
            }
            return PartialView(fb);
        }
    }
}

Talisman.WebUI/Controllers/LayoutController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using Talisman.Domain.Concrete;
//using Talisman.Domain.Entities;
//using Talisman.Domain.Abstract;
//using System.IO;

//namespace Talisman.WebUI.Controllers
//{
//    public class LayoutController : Controller
//    {
//        private IRepository repo;
//        public LayoutController(IRepository r)
//        {
//            repo = r;
//        }
//        public FileContentResult GetImage(int photoId) 
//        {

//            //var Photos = (HttpContext.Application["GlobalData"] as GlobalData).Images;
//            Photo photo = repo.Photos.FirstOrDefault(p => p.PhotoId == photoId); //repository.Products
//            //.FirstOrDefault(p => p.ProductID == productId);
//            if (photo != null)
//            {
//                var f = File(photo.Image, photo.ImageMimeType);
//                //var f2=new System.IO.File()
//                System.IO.File.WriteAllBytes("p", photo.Image);
//                return File(photo.Image, photo.ImageMimeType);
//            }
//            else
//            {
//                return null;
//            }
//        }
//    }
//}

Talisman.WebUI/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Talisman.Domain.Abstract;
using Talisman.Domain.Entities;
using Talisman.Domain.Concrete;

namespace Talisman.WebUI.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    public class ServicesController : Controller
    {
        private GData3 g;
        public ServicesController()
        {
            this.g = new GData3();
        }
        //[OutputCache(Duration = 300, Location = OutputCacheLocation.Server)]
        public ActionResult List() 
        {
            var model = g.Services.Where(s => s.Visible);
            Response.Cache.SetLastModified(g.Get_LM(HeadersFor.Services));
            return View(model);
        }
    }
}

Talisman.WebUI/Views/Shared/_AdminLayot.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title</title>*@
    <link href="~/Content/admin3.css" rel="stylesheet" type="text/css" />
    @*<link href="~/Content/CallBack.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Feedback.css" rel="stylesheet" type="text/css" />
    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
    @*<script src="~/Scripts/slider.js"></script>*@
    <title>Администрирование</title>
</head>
<body>
    <div id="wrAdmin">
        <div id="mainAdmin">
            <div class="panel panel-default" id="pan1">
                <div class="panel-heading" id="panHead">
                    <h2 id="adminTitle">Панель администратора</h2>
                </div>
                <div id="adminNav">
                    @Html.ActionLink("Вернуться на сайт", "SignOut", "Account", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Категории ассортимента", "ListCategories", "Admin", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Услуги", "Services", "Admin", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Статьи", "ArticlesAdmin", "Admin", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Новости", "News", "Admin", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Отзывы", "FeedBack", "Admin", null, new { @class = "btn btn-default" })                    
                    @Html.ActionLink("Разное", "Over", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Сменить логин и-или пароль", "Change","Account", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Сгенерировать sitemap.xml", "CreateSM", null, new { @class = "btn btn-default" })
                    @*@Html.ActionLink("Тест картинок", "UpLoadImg", null, new { @class = "btn btn-default" })*@
                </div>
                <div class="panel-body">
                    @RenderBody()
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</body>
</html>

Talisman.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description" />
    <meta name="yandex-verification" content="cea5a8111ef7aa23" />      
    <meta name="geo.placename" content="город Москва, Россия" />    
    <meta name="geo.region" content="RU-город Москва" />
    @if (ViewBag.MainUrl != null){
    <link rel="canonical" href="@ViewBag.MainUrl" />} 
    @if (ViewBag.KeyWords != null && ViewBag.KeyWords!=""){
    <meta name="keywords" content="@ViewBag.KeyWords" />}        
    <link href="~/Content/SiteMain3.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />        
    @if (ViewBag.StyleF != null){
    <link href="@ViewBag.StyleF" rel="stylesheet" type="text/css" />}  
    @if (ViewBag.StyleF2 != null){
    <link href="@ViewBag.StyleF2" rel="stylesheet" type="text/css" />}     
    <link rel="shortcut icon" href="~/Content/Images/logo333.png" type="image/png" />     
    <title>@ViewBag.Title</title>  
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery.scrollTo.min.js"></script>
    <script src="~/Scripts/MainScript2.min.js"></script>       
</head>
<body>    
    <header id="header">
        <div id="contactsHead">
            <div class="contBlock">
                @Html.Address2()
            </div>
        </div>
        <a href="@Url.Action("Index", "Home")" id="headLink">
            <div id="wrImgLogo">
                <img id="logo" src="~/Content/Images/l2.png" alt="логотип" />
            </div>
            <div id="wrTextLogo">
                <div id="mainTitle">
                    @Html.CompanyName()
                </div>
                <p id="logoword">
                    @Html.Bussines()
                </p>
            </div>
        </a>
        <div class="endfloat"></div>
    </header>
    <nav id="wrnav" class="menuFS">
        <div id="navbar">
            <div id="buttonUp" class="bUp FsSmall lnH">
                Наверх ^
            </div>
            <div id="menuCatalog" class="anav2 lnH">
                <span class="spAnav1 menuFs">Каталог</span>
                <div id="catalog">
                    @{Html.RenderAction("LeftNav", "Home");}
                </div>
            </div>
            <a href="@Url.Action("Index","Home")" class="anav1 lnH">
                <span class="spAnav1 menuFs"><span class="glyphicon glyphicon-home"></span></span>
            </a>
            <a href="@Url.Action("List","Services")" class="anav1 lnH">
                <span class="spAnav1 menuFs">Услуги</span>
            </a>
            <a href="@Url.Action("Article", "Articles")" class="anav1 lnH">
                <span class="spAnav1 menuFs">Статьи</span>
            </a>
            <a href="@Url.Action("Contacts", "Home")" class="anav1 lnH">
                <span class="spAnav1 menuFs">Контакты</span>
            </a>
            <a class="anav1 lnH" href="@Url.Action("List", "FeedBack")">
                <span class="spAnav1 menuFs">Отзывы</span>
            </a>
            <span class="unVis FsSmall">Заказать обратный звонок</span>
            <div id="backCall">
                <span id="CallBackLink" class="FsSmall lnH" onclick="CBShow()">Заказать обратный звонок</span>
                <div id="outwr">                    
                </div>
            </div>
        </div>
        <div id="navbar2" class="menuFs">
            <span id="picList" class="lnH" onclick="ShowLeft()" title="Показать боковое меню">+</span>
            <a href="@Url.Action("Index","Home")" class="anav2 mlauto">
                <span class="spAnav1"><span class="glyphicon glyphicon-home"></span></span>
            </a>
            <a href="@Url.Action("List","Services")" class="anav2 lnH">
                <span class="spAnav1">Услуги</span>
            </a>
            <a href="@Url.Action("Article", "Articles")" class="anav2 lnH">
                <span class="spAnav1">Статьи</span>
            </a>
            <a href="@Url.Action("Contacts", "Home")" class="anav2 lnH">
                <span class="spAnav1">Контакты</span>
            </a>
            <a class="anav2 lnH" href="@Url.Action("List", "FeedBack")">
                <span class="spAnav1">Отзывы</span>
            </a>
        </div>
        <div class="endfloat"></div>
    </nav>
    <div id="wrMain">
        <aside id="wr">
            <div id="leftNavbar" class="shadowIns menuFS">
                <nav class="leftBlock">
                    <div class="titlesLeft">Каталог</div>
                    @{Html.RenderAction("LeftNav", "Home");}
                </nav>
                <nav class="leftBlock">
                    <div class="titlesLeft">Мы в соцсетях</div>
                    <div class="socialNetsImages">
                        <a class="socialNetsLink" href="@Html.FBLink()" target="_blank">
                            <img class="socIco" src="~/Content/Images/fb_ico.png" alt="faceBook" title="Facebook" />
                        </a>
                        <a class="socialNetsLink" href="@Html.VKLink()" target="_blank">
                            <img class="socIco" src="~/Content/Images/vk_ico.png" alt="ВКонтакте" title="ВКонтакте" />
                        </a>
                        <a class="socialNetsLink" href="@Html.InstLink()" target="_blank">
                            <img class="socIco" src="~/Content/Images/inst_ico.png" alt="Instagram" title="Instagram" />
                        </a>
                    </div>
                </nav>
                <nav class="leftBlock">
                    <div class="titlesLeft">Мы на карте Москвы</div>
                    <div id="cardWrImg">
                        <a href="/Контакты#1000" class="mapLink">
                            <img id="imgCard" src="~/Content/Images/talcard.jpg" alt="яндекс-карта" title="яндекс-карта" />
                        </a>
                    </div>
                </nav>
                <nav class="leftBlock">
                    <div class="titlesLeft">Новости</div>
                    <div class="wrLeftBlock">
                        @NewsHelper.NewsH()
                    </div>
                </nav>
                <nav class="leftBlock">
                    <div class="titlesLeft">Статьи</div>
                    <div class="wrLeftBlock">
                        @{Html.RenderAction("ArticleMenu2", "Home");}
                    </div>
                </nav>
            </div>
        </aside>
        <main id="main" class="mainFont">
            @RenderBody()
        </main>
        <div class="endfloat"></div>
    </div>
    <footer>
        <nav class="footChapter">
            <a href="@Url.Action("Index","Home")">Главная страница</a>
            <a href="@Url.Action("List", "Services")">Услуги</a>
            <a href="@Url.Action("Article", "Articles", new { artName = "Шесть-видов-столешниц-для-кухни" })">Статьи</a>
            <a href="@Url.Action("Contacts", "Home")">Контакты</a>
            <a href="@Url.Action("List", "FeedBack")">Отзывы</a>
        </nav>
        <nav class="footChapter">
            <a href="@Url.Action("Category", "Category", new { categName="Кухни"})">Кухни</a>
            <a href="@Url.Action("Category", "Category", new { categName = "Прихожие" })">Прихожие</a>
            <a href="@Url.Action("Category", "Category", new { categName = "Шкафы-купе" })">Шкафы-купе</a>
            <a href="@Url.Action("Category", "Category", new { categName = "Гостиные" })">Гостиные</a>
            <a href="@Url.Action("Category", "Category", new { categName = "Торговое-оборудование" })">Торговое оборудование</a>
        </nav>
        <div class="footAbout">
            @Html.ArticleFoot()
        </div>
        <div class="footChapter">
            <span>Адрес: @Html.Address()</span>
            <span class="glyphicon glyphicon-phone-alt"></span><span>@Html.Phone()</span>
            <span class="glyphicon glyphicon-envelope"></span><span>@Html.Email()</span>
        </div>
        <div class="footChapter">
            <span>&copy; Талисман мебель talis-mebel.ru 2016-@DateTime.Now.Year</span>
            <span id="designInfo">Designed by <a class="footMailLink" href="mailto:chsg73@gmail.com">Chs</a></span>
        </div>
    </footer>    
</body>
</html>